# Generated by Django 2.2 on 2022-05-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('link1', models.URLField()),
                ('link2', models.URLField()),
                ('link3', models.URLField()),
            ],
        ),
    ]
