# Generated by Django 2.2 on 2022-05-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='link1',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='link2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='link3',
            field=models.URLField(blank=True),
        ),
    ]
