# Generated by Django 2.2 on 2022-04-24 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220413_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='vote_a',
            field=models.ManyToManyField(blank=True, related_name='vote_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='vote_b',
            field=models.ManyToManyField(blank=True, related_name='vote_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
