# Generated by Django 2.2 on 2022-05-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_connect_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='content',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='content_a',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='content_b',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
