# Generated by Django 2.2 on 2022-05-16 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20220515_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VoteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content_a', models.CharField(blank=True, max_length=50)),
                ('content_b', models.CharField(blank=True, max_length=50)),
                ('dt_created', models.DateTimeField()),
                ('dt_modified', models.DateTimeField()),
                ('open', models.BooleanField(default=True)),
                ('connect_user', models.ManyToManyField(blank=True, related_name='connect_user_history', to=settings.AUTH_USER_MODEL)),
                ('vote_a', models.ManyToManyField(blank=True, related_name='vote_a_history', to=settings.AUTH_USER_MODEL)),
                ('vote_b', models.ManyToManyField(blank=True, related_name='vote_b_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
