# Generated by Django 2.2 on 2022-05-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20220516_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votehistory',
            name='open',
        ),
        migrations.AlterField(
            model_name='votehistory',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
