# Generated by Django 2.2 on 2022-05-16 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_votehistory_connect_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votehistory',
            name='dt_modified',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='content_vote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='votehistory',
            name='content_vote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='votehistory',
            name='dt_end',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
