# Generated by Django 2.2 on 2022-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20220516_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_category',
            field=models.CharField(choices=[('시사이슈', '시사이슈'), ('연예', '연예'), ('스포츠', '스포츠'), ('기타', '기타')], default='기타', max_length=50),
        ),
    ]
