# Generated by Django 2.2 on 2022-05-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatroom_chat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chat_category',
            field=models.CharField(choices=[('시사이슈', '시사이슈'), ('연예', '연예'), ('스포츠', '스포츠'), ('주식', '주식'), ('게임', '게임')], max_length=50),
        ),
    ]
